// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwykiNnNXngGWTwyZVErbh_jiibMk6P60',
    appId: '1:240912771850:web:ba621610b140fdc7da68f3',
    messagingSenderId: '240912771850',
    projectId: 'tarea6-clon',
    authDomain: 'tarea6-clon.firebaseapp.com',
    storageBucket: 'tarea6-clon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC-bKxKzeKLf_JNEyY2lH7-eOMisJRo48',
    appId: '1:240912771850:android:15bc42cbad63788eda68f3',
    messagingSenderId: '240912771850',
    projectId: 'tarea6-clon',
    storageBucket: 'tarea6-clon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdsKLNOgPNF8mDzdYcugp7ysVdkZXiHkw',
    appId: '1:240912771850:ios:e24cc52c3e7576f6da68f3',
    messagingSenderId: '240912771850',
    projectId: 'tarea6-clon',
    storageBucket: 'tarea6-clon.firebasestorage.app',
    iosBundleId: 'com.example.tarea6Clon',
  );
}
